# Generated by Django 3.2.10 on 2021-12-11 15:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default=0, max_length=20)),
            ],
            options={
                'db_table': 'social_platform',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(verbose_name='date published')),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('date_birth', models.DateField()),
                ('email', models.CharField(max_length=254)),
                ('username', models.CharField(max_length=254)),
                ('social_login_id', models.CharField(blank=True, max_length=50)),
                ('social', models.ForeignKey(blank=True, default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='pick_restful.socialplatform')),
            ],
        ),
    ]
